language: android
android:
	components:
	
	#The BuilsTools version used by this project
	- build-tools-23.0.2
	
	#The SDK version used to compile this project
	- android-25
	
	- platform-tools
	- tools
	
	# Extras
	- extra-google-google_play_services
	- extra-google-m2repository
	- extra-android-m2repository
	- addon-google_apis-google-19
	
	# "avoid uploading the cache after every build"
before_cache:
	- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
	- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
    directories:
		- $HOME/.gradle/caches/
		- $HOME/.gradle/wrapper/

	
	